from selenium.webdriver.common.by import By

class Locators:
    ADD_NEW_QUESTION_BUTTON = ('button.AddRecordBtn', 'css')
    SAVE_BUTTON = ('save-button', 'id')
    CLOSE_BUTTON = ('close-button', 'id')
    DISPLAY_MESSAGE = ('notice', 'id')
    PARSLEY_REQUIRED = ('parsley-required', 'class')
    PARSLEY_MAXFILESIZE = ('parsley-maxFileSize', 'class')
    PARSLEY_FILEEXTENSION = ('parsley-fileextension', 'class')
    GET_QUESTION_TEXT = ('td.EditData', 'css')
    PARSLEY_PATTERN = ('parsley-pattern', 'class')
    TABLE_ROW_COUNT = ('tbody#demo tr', 'css')
    DELETE_BUTTON = ('Delete', 'id')
    PARSLEY_MAXLENGTH = ('parsley-maxlength', 'class')
    EDIT_BUTTON = ('editButton', 'class')
    INPUT_OPTION_A = ('optionA','name')
    INPUT_OPTION_B = ('optionB','name')
    INPUT_OPTION_C = ('optionC','name')
    INPUT_OPTION_D = ('optionD','name')
    CHECKED_ON_CORRECT_OPTION = ('//input[@value="optionB"]', 'xpath')
    
class LoginPageLocators:
    INPUT_USERNAME = ('username', 'name')
    INPUT_PASSWORD = ('password', 'name')
    LOGIN_BUTTON = ('login_button', 'id')
    CLICK_TEXT_ALLOW_AUTHENTICATED_USER_XPATH = ('Allow Authenticated User', "link text")
    CLICK_TEXT_ADD_SUBJECT_XPATH = ('Add Subject', "link")
    CLICK_TEXT_MULTIPLE_IMAGE_CHOICE_QUESTION_XPATH = ('Multiple Image Choice Question', "link")
    CLICK_TEXT_MULTIPLE_CHOICE_QUESTION_XPATH = ('Multiple Choice Question', "link")
    CLICK_TEXT_IMAGE_BASED_MULTIPLE_CHOICE_QUESTION_XPATH = ('Image Based Multiple Choice Questions', "link")
    CLICK_TEXT_SUBJECTIVE_QUESTION_XPATH = ('Subjective Questions', "link")
    CLICK_TEXT_IMAGE_BASED_SUBJECTIVE_QUESTION_XPATH = ('Image Based Subjective Questions', "link")
    
class SubjectPageLocators:
    INPUT_SUBJECT = ('subject', 'name')
    GET_TEXT_SUBJECT = ('//*[@id="demo"]/tr[1]/td[1]', 'xpath')
    
class MultipleImageChoiceQuestionPageLocators:
    INPUT_QUESTION_TITLE = ('MICQ_title', 'id')
    INPUT_SUBJECT = ('//select[@id="MICQ_subject"]/option[6]', 'xpath')
    CHECKED_ON_CORRECT_OPTION = ('//input[@value="optionB"]', 'xpath')
    CLOSE_BUTTON = ('//button[@value="close"]', 'xpath')
    SAVE_BUTTON = ('//button[@value="Save"]', 'xpath')
    SEARCH_BY_QUESTION = ('//input[@name="question_title"]', 'xpath')
    SEARCH_BUTTON = ('//input[@value="Search"]', 'xpath')
    CLICK_EDIT_BUTTON_SELECT_SUBJECT_DROPDOWN = ('//select[@id="MICQ_subject"]/option[1]', 'xpath')
    UPDATE_INPUT_SUBJECT = (By.XPATH, '//select[@id="MICQ_subject"]/option[6]')
    SEARCH_BY_SUBJECT = (By.ID, 'id_subject')

class MultipleChoiceQuestionPageLocators:
    INPUT_SUBJECT = ('//select[@id="MCQ_subject"]/option[6]', 'xpath')
    INPUT_SUBJECT_NEW = ('//select[@id="MCQ_subject"]/option[3]', 'xpath')
    EXCEL_SUBJECT = ('//select[@id="MCQ_subject"]/option[2]', 'xpath')
    INPUT_QUESTION_TITLE = ('MCQ_title', 'id')
    OPTION_A = ('MCQ_optionA', 'id')
    OPTION_B = ('MCQ_optionB', 'id')
    OPTION_C = ('MCQ_optionC', 'id')
    OPTION_D = ('MCQ_optionD', 'id')
    SEARCH_QUESTION_TITLE = ('MCQ_title_search', 'id')
    SEARCH_BUTTON = ('//button[@value="Search"]', 'xpath')
    TABLE_QUESTION_TITLE = ('//tr/td/h5', 'xpath')
    SEARCH_SUBJECT = ('//select[@id="MCQ_subject_search"]/option[5]', 'xpath')
    WITHOUT_SEARCH_SUBJECT = ('//select[@id="MCQ_subject_search"]/option[1]', 'xpath')
    WRONG_SUBJECT = ('//select[@id="MCQ_subject_search"]/option[8]', 'xpath')
    ENGLISH_SUBJECT = ('//select[@id="MCQ_subject_search"]/option[6]', 'xpath')
    TABLE_QUESTION_TITLE_FIRST = ('//tr[1]/td[1]/h5', 'xpath')
    DELETE_BUTTON = ('btn-danger', 'class')
    EDIT_BUTTON = ('edit_mcq', 'class')
    CANCEL_BUTTON = ('close-dialoge', 'id')
    WITHOUT_SEARCH_SUBJECT_MCQ = ('//select[@id="MCQ_subject"]/option[1]', 'xpath')

class ImageBasedMultipleChoiceQuestionPageLocators:
    INPUT_SUBJECT = ('//select[@id="image_MCQ_subject"]/option[6]', 'xpath')
    QUESTION_TITLE = ('//input[@id="image_MCQ_title"]', 'xpath')
    IMAGE = ('MCQ_image_upload', 'id')
    WITHOUT_SUBJECT = ('//select[@id="image_MCQ_subject"]/option[1]', 'xpath')
    TYPING_TEST_SUBJECT = ('//*[@id="image_MCQ_subject"]/option[3]', 'xpath')
    EXCEL_SUBJECT = ('//*[@id="image_MCQ_subject"]/option[2]', 'xpath')
    SEARCH_QUESTION_TITLE = ('id_question_title', 'id')
    SEARCH_SUBJECT = ('//select[@id="id_subject"]/option[6]', 'xpath')
    WITHOUT_SEARCH_SUBJECT = ('//select[@id="id_subject"]/option[1]', 'xpath')
    WRONG_SUBJECT = ('//select[@id="id_subject"]/option[5]', 'xpath')
    EDIT_BUTTON = ('a.Edit', 'css')

class SubjectiveQuestionPagelocators:
    INPUT_SUBJECT = ('id_subjects', 'id')
    INPUT_PASSAGE = ('id_passage', 'id')
    INPUT_QUESTION_TITLE = ('id_question_title', 'id')
    INPUT_ANSWER_KEY = ('id_answer_key', 'id')
    INPUT_INSTRUCTION = ('id_instructions', 'id')
    SEARCH_QUESTION = ('searchquestion', 'id')
    LIST_ELEMENT = ('panel-heading', 'class')
    SEARCH_SUBJECT = ('id_question_id', 'id')
    TABLE_QUESTION_TITLE = ('EditData', 'class')

class ImageBasedSubjectiveQuestionPageLocators:
    INPUT_SUBJECT = ('IBSQ_subject', 'id')
    INPUT_QUESTION = ('IBSQ_question', 'id')
    INPUT_ANSWER_KEY = ('IBSQ_answer_key', 'id')
    INPUT_IMAGE = ('IBSQ_image_upload', 'id')
    TABLE_QUESTION_TITLE = ('EditData', 'class')
    SEARCH_QUESTION = ('IBSQ_question_search', 'id')
    SEARCH_SUBJECT = ('IBSQ_subject_search', 'id')
